spring.application.name=fintechNovo
# Endereço do banco de dados
spring.datasource.url=jdbc:oracle:thin:@l8cn0atovwb2y1vj_high?TNS_ADMIN=${WALLET_PATH:src/main/resources/wallet}
# Usuário do banco de dados
spring.datasource.username=${DB_USER}
# Senha do banco de dados
spring.datasource.password=${DB_PASSWORD}

# Mostrar as instruções SQL
# executadas no banco de dados
spring.jpa.show-sql=true
# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
# Dialeto para o Spring entender como conversar com o Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ddl-auto=update faz com que o Spring crie ou atualize as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

