spring.application.name=fintechNovo

spring.datasource.url=jdbc:oracle:thin:@l8cn0atovwb2y1vj_high?TNS_ADMIN=${WALLET_PATH:src/main/resources/wallet}

spring.datasource.username=${DB_USER}

spring.datasource.password=${DB_PASSWORD}


spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


spring.jpa.hibernate.ddl-auto=update

